addons:
  apt:
    packages:
    - libgmp-dev
after_success:
- stack tools/upload-package.hs
before_install:
- sh tools/install-stack.sh
cache:
  directories:
  - $HOME/.local/bin
  - $HOME/.stack
language: c
script:
- stack setup
- stack build --pedantic
- stack sdist
sudo: false
