category: Utility
description: Autoexporter automatically re-exports modules.
executables:
  autoexporter:
    dependencies:
    - base
    - autoexporter
    main: Main.hs
    source-dirs: source/executable
extra-source-files:
- CHANGELOG.markdown
- package.yaml
- README.markdown
- stack.yaml
ghc-options:
- -Wall
github: tfausak/autoexporter
library:
  dependencies:
  - base >=4.7 && <4.10
  - Cabal >=1.22 && <1.25
  - directory >=1.2.5 && <1.4
  - filepath >=1.3 && <1.5
  source-dirs: source/library
license: MIT
license-file: LICENSE.markdown
maintainer: Taylor Fausak
name: autoexporter
synopsis: Automatically re-export modules.
version: '1.1.1'
